package com.erp.common.IDAO;
import com.erp.common.model.User;

public interface IUserDAO {
	
	public static final String SELECT_ONE_USER = "selectOneUser";
	
	public abstract int deleteByPrimaryKey(String userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
	public abstract User selectByPrimaryKey(String userId);

    /**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_user
	 *
	 * @mbggenerated Fri Feb 05 22:09:31 CST 2016
	 */

}
